### ISSUE TITLE
Fails to build with abseil-20230125.3: /usr/local/include/absl/base/policy_checks.h:79:2: error: "C++ versions less than C++14 are not supported."

### ISSUE THREAD

**Issue by yurivict** [google/s2geometry#317]
```
In file included from /usr/ports/graphics/s2/work/s2geometry-0.10.0/src/s2/id_set_lexicon.cc:18:
In file included from /usr/ports/graphics/s2/work/s2geometry-0.10.0/src/s2/id_set_lexicon.h:26:
In file included from /usr/ports/graphics/s2/work/s2geometry-0.10.0/src/s2/sequence_lexicon.h:26:
In file included from /usr/ports/graphics/s2/work/s2geometry-0.10.0/src/s2/util/gtl/dense_hash_set.h:127:
In file included from /usr/ports/graphics/s2/work/s2geometry-0.10.0/src/s2/base/port.h:38:
In file included from /usr/local/include/absl/base/config.h:86:
/usr/local/include/absl/base/policy_checks.h:79:2: error: "C++ versions less than C++14 are not supported."
#error "C++ versions less than C++14 are not supported."
 ^
1 error generated.
```

Please bump the C++ version requirement to fix this.

Version: 0.10.0
FreeBSD 13.2
clang-15

**Comment by jmr** [comment]
This was already done in c5f46a4. We'll make a 0.11 release including that soon.  Sorry for the inconvenience!

**Comment by jmr** [comment]
https://github.com/google/s2geometry/releases/tag/v0.11.0 has this fix.
